worker_processes 1;

events {
    worker_connections 1024;
}

http {
    server {
        listen 80;
        server_name localhost;

        location /pages/ {
            root /usr/share/nginx/html;
            index index.html;
            try_files $uri $uri/ /pages/index.html;
        }

        error_page 404 /404.html;
        location = /404.html {
            internal;
        }

        location /pages/assets/ {
            root /usr/share/nginx/html;
        }
    }
}
